apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::709677830056:role/eksctl-simple-jwt-api1-nodegroup-n-NodeInstanceRole-Yit8fVzHBaXv
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes
    - rolearn: arn:aws:iam::709677830056:role/UdacityFlaskDeployCBKubectlRole1
      username: build
      groups:
      - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::709677830056:user/adminuser
      username: adminuser
      groups:
      - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
